spring:
  application:
    name: tstack
  threads:
    virtual:
      enabled: true

application:
  title: Tstack
  version: @project.version@

  datasource:
    url: jdbc:h2:${HOME}/.tstack/tstack
    driver-class-name: org.h2.Driver


#logging:
#  level:
#    root: ERROR

